# Generated by Django 2.1.3 on 2019-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='apellido',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='dni',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='curso',
            name='telefono',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
