# Generated by Django 2.1.3 on 2019-01-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190104_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='dni',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
